name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 8 * * 6'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: coq-community/docker-coq-action@v1
        with:
          coq_version: latest
          before_script: |
            sudo chown -R coq:coq .
          script: |
            make -j$(nproc) check
      - name: Revert permissions
        # to avoid a warning at cleanup time
        run: sudo chown -R 1001:116 .
